services:
  mysql-server:
    image: mysql:8.0-oracle
    container_name: mysql-server
    restart: unless-stopped
    networks:
      zabbix-net:
        ipv4_address: 172.20.240.2
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - zabbix_mysql_data:/var/lib/mysql
    command: >
      --character-set-server=utf8
      --collation-server=utf8_bin
      --default-authentication-plugin=mysql_native_password

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:ubuntu-7.2-latest
    container_name: zabbix-java-gateway
    restart: unless-stopped
    networks:
      zabbix-net:
        ipv4_address: 172.20.240.3

  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:ubuntu-7.2-latest
    container_name: zabbix-server-mysql
    restart: unless-stopped
    depends_on:
      - mysql-server
      - zabbix-java-gateway
    ports:
      - "10051:10051"
    networks:
      zabbix-net:
        ipv4_address: 172.20.240.4
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: root
      ZBX_JAVAGATEWAY: zabbix-java-gateway
      ZBX_ENABLE_AGENT: true
      ZBX_SERVER_HOST: zabbix-server-mysql
      ZBX_HOSTNAME: zabbix-server-mysql
      ZBX_SERVER_IP: 172.20.240.4

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-7.2-latest
    container_name: zabbix-web-nginx-mysql
    restart: unless-stopped
    depends_on:
      - zabbix-server-mysql
    ports:
      - "80:8080"
      - "8080:8080"
    networks:
      zabbix-net:
        ipv4_address: 172.20.240.5
    environment:
      ZBX_SERVER_HOST: zabbix-server-mysql
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: root
      PHP_TZ: America/Sao_Paulo

  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-7.2-latest
    container_name: zabbix-agent
    restart: unless-stopped
    depends_on:
      - zabbix-server-mysql
    networks:
      zabbix-net:
        ipv4_address: 172.20.240.6
    environment:
      ZBX_SERVER_HOST: zabbix-server-mysql
      ZBX_HOSTNAME: zabbix-server-mysql
      ZBX_SERVER_IP: 172.20.240.4

networks:
  zabbix-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.240.0/20

volumes:
  zabbix_mysql_data:
    external: true